books/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^search/(?P<content>\w+)/$|search/$', views.search, name='search'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'loginConfirm/$', views.loginConfirm, name='loginConfirm'),
    url(r'libadmin/$', views.libadmin, name='libadmin')
]

library/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'library.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('books.urls', namespace='books')),
]

books/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Administrator(models.Model):
    user = models.OneToOneField(User)
    create_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.name

class Author(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class PublishCompany(models.Model):
    name = models.CharField(max_length=60)

    def __str__(self):
        return self.name

class Books(models.Model):
    book_id = models.CharField(max_length=60, primary_key=True)
    category = models.CharField(max_length=60)
    name = models.CharField(max_length=60)
    pub_com = models.ForeignKey(PublishCompany)
    pub_year = models.CharField(max_length=5)
    author = models.ForeignKey(Author)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    amount = models.IntegerField(default=1)
    left = models.IntegerField()

    search = models.TextField(default='')

    def save(self, *args, **kwargs):
        self.search = self.book_id + ' ' + self.name + ' ' + self.category + ' ' + self.pub_com.name + ' ' + self.author.name + ' '
        if self.left is None:
            self.left = self.amount
        super(Books, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

class CardType(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name

class Card(models.Model):
    card_id = models.CharField(max_length=20, primary_key=True)
    limit = models.IntegerField(default=4)
    fare = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    card_type = models.ForeignKey(CardType)

    def __str__(self):
        return self.card_id

class Record(models.Model):
    book = models.ForeignKey(Books)
    card = models.ForeignKey(Card)
    borrow_time = models.DateTimeField(auto_now_add=True)
    return_time = models.DateTimeField(null=True)
    admin = models.ForeignKey(User)

    def __str__(self):
        return self.book.book_id

books/views.py
import json
import datetime
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.template import RequestContext
from django.contrib.auth import authenticate, login as djangoLogin, logout as djangoLogout
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.core import serializers
from django.utils import timezone

from books import models
# Create your views here.


def index(request):
    context = RequestContext(request)
    return render(request, 'books/index.html', context)


def search(request, content):
    context = RequestContext(request)
    try:
        books = models.Books.objects.filter(search__contains=content)
        context.push({'books': books})
    except:
        context.push({'none': True})
    return render(request, 'books/search.html', context)


def login(request):
    return render(request, 'books/login.html', {})


def logout(request):
    if request.user.is_authenticated():
        djangoLogout(request)
    return HttpResponseRedirect(reverse('books:index'))


def loginConfirm(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None and user.is_active:
        djangoLogin(request, user)
        return HttpResponseRedirect(reverse('books:index'))
    else:
        return render(request, 'books/login.html', {'msg': 'invalid username or password'})


@login_required(login_url='/login/')
def libadmin(request):
    context = {
        'msg': '',
        'err': False
    }
    
    def getPublishCompany(name):
        try:
            p = models.PublishCompany.objects.get(name=name)
        except:
            p = models.PublishCompany.objects.create(name=name)
        return p

    def getAuthor(name):
        try:
            p = models.Author.objects.get(name=name)
        except:
            p = models.Author.objects.create(name=name)
        return p

    def getCardType(name):
        try:
            p = models.CardType.objects.get(name=name)
        except:
            p = models.CardType.objects.create(name=name)
        return p

    def opError(msg=''):
        context['msg'] = msg
        context['err'] = True


    if request.method == 'GET':
        if len(request.GET) == 0:
            context = RequestContext(request)
            return render(request, 'books/libadmin.html', context)

    elif request.method == 'POST':
        data = json.loads(request.body.decode('utf-8'))
        if data['action'] == 'add_book':
            try:
                book = models.Books.objects.get(book_id=data['book_id'])
            except:
                newbook = models.Books.objects.create(
                    pub_com = getPublishCompany(data['pub_com']),
                    book_id = data['book_id'],
                    name = data['name'],
                    pub_year = data['pub_year'],
                    price = data['price'],
                    amount = data['amount'],
                    left = data['amount'],
                    category = data['category'],
                    author = getAuthor(data['author'])
                )
                try:
                    newbook.save()
                except Exception as e:
                    opError(str(e))
            else:
                book.amount += int(data['amount'])
                book.left += int(data['amount'])
                book.save()

        if data['action'] == 'add_card':
            try:
                newcard = models.Card.objects.create(
                    card_id = data['card_id'],
                    limit = data['limit'],
                    card_type = getCardType(data['card_type'])
                )
                if newcard is not None:
                    newcard.save()
                else:
                    opError('Add Card Failed, Please Check if card is conflict')
            except Exception as e:
                opError(str(e))

        if data['action'] == 'book_borrow':
            try:
                book = models.Books.objects.get(book_id=data['book_id'])
                card = models.Card.objects.get(card_id=data['card_id'])
                if book.left > 0:
                    book.left -= 1
                    book.save()
                    record = models.Record.objects.create(
                        book = book,
                        card = card,
                        admin = request.user
                    )
                    record.save()
                else:
                    record = models.Record.objects.get(book=book, card=card, return_time = None)
                    if type(record) is list:
                        record = record.order_by('-borrow_time')[0]
                    msg = 'No book Left, Nearest Return time:' + (record.borrow_time + datetime.timedelta(days=40)).strftime("%y-%m-%d")
                    opError(msg)
            except Exception as e:
                opError(str(e))
                # opError('Invalid Book Id or Card Id')
            
        if data['action'] == 'book_return':
            try:
                book = models.Books.objects.get(book_id=data['book_id'])
                card = models.Card.objects.get(card_id=data['card_id'])
                record = models.Record.objects.get(book=book, card=card, return_time = None)
                if type(record) is list:
                    record = record[0]

                record.return_time = timezone.now()
                record.save()
                book.left += 1
                book.save()
            except Exception as e:
                opError(str(e))

        if data['action'] == 'del_card':
            try:
                card = models.Card.objects.get(card_id=data['card_id'])
                try:
                    record = models.Record.objects.get(card=card, return_time = None)
                except:
                    card.delete()
                else:
                    opError('This card holder has not returned all the books')
            except:
                opError('No card matched')

        if data['action'] == 'del_book':
            try:
                book = models.Books.objects.get(book_id=data['book_id'])
                try:
                    record = models.Record.objects.get(book=book, return_time=None)
                except:
                    book.delete()
                else:
                    opError('You cannot remove the book from the library, for there are copies remain un-returned')
            except:
                opError('No book matched')

        if data['action'] == 'card_book':
            try:
                cards = models.Card.objects.get(card_id=data['card_id'])
                if type(cards) is not list:
                    cards = [cards]
                records = models.Record.objects.filter(card__in=cards)
                if type(records) is not list:
                    records = [records]
                ids = []
                for record in records:
                    ids.append(record[0].book.book_id)
                books = models.Books.objects.filter(book_id__in=ids)
                context['books'] = serializers.serialize('json', books)
            except Exception as e:
                opError(str(e))

        jsondata = json.dumps(context)
        return HttpResponse(jsondata, content_type="application/json")

books/templates/books/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Super Books</title>
    <link rel="stylesheet" href="{% static 'books/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'books/css/base.css' %}" >
    {% block staticCSS %} {% endblock %}
    <script src="{% static 'books/js/jquery-2.1.3.min.js' %}"></script>
</head>
<body>
<div class="container">
    <nav class="nav" id="header"> 
        <h1 class="col-md-9"><a href="/">Super Books</a></h1>
        <div id="header-status" class="col-md-3">
            {% if user.is_authenticated %}
            <span>Hi, {{ user.username }}</span> 
            <a href="/libadmin/">Management</a>
            <a href="/logout/">Log out</a>
            {% else %}
            <a href="/login/">Log in</a>
            {% endif %}
        </div>
    </nav>
    <div class="col-md-12">
        {% block container %} {% endblock %}
    </div>
</div>
{% block staticJS %} {% endblock %}
</body>
</html>

books/templates/books/index.html
{% extends "books/base.html" %}
{% load staticfiles %}

{% block staticCSS %}
<link rel="stylesheet" href="{% static 'books/css/index.css' %}"/>
{% endblock %}

{% block container %}
<div id="message" class="alert alert-danger" role="alert" style="display: none;"></div>

<form class="form-inline">
	<div class="form-group">
		<input type="text" class="form-control" name="content" id="search-content" placeholder="Please type the book you want">
	</div>
	<button type="submit" class="btn btn-primary" id="search-submit">Search</button>
</form>
{% endblock %}

{% block staticJS %}
<script src="{% static 'books/js/search.js' %}"></script>
{% endblock %}

books/templates/books/libadmin.html
{% extends "books/base.html" %}
{% load staticfiles %}

{% block staticCSS %}
<link rel="stylesheet" href="{% static 'books/css/libadmin.css' %}"/>
{% endblock %}
{% block container %}
<div id="side-bar" class="col-md-3">
    <ul class="nav">
        <li><a class="side-bar-tag" href="javascript:void(0)" id="add-book">Add Books</a></li>
        <li><a class="side-bar-tag" href="javascript:void(0)" id="del-book">Delete Books</a></li>
        <li><a class="side-bar-tag" href="javascript:void(0)" id="add-card">Add Card</a></li>
        <li><a class="side-bar-tag" href="javascript:void(0)" id="del-card">Delete Card</a></li>
        <li><a class="side-bar-tag" href="javascript:void(0)" id="book-borrow">Borrow</a></li>
        <li><a class="side-bar-tag" href="javascript:void(0)" id="book-return">Return</a></li>
        <li><a class="side-bar-tag" href="javascript:void(0)" id="book-file">Operate by JSON</a></li>
    </ul>
</div>
<div id="op-field" class="col-md-9">
		<div class="mng-tag hidden" id="add-book-tag">
		<form class="form-horizontal">
			<div class="form-group">
			<label class="col-md-3 control-label">Book ID</label>
			<div class="col-md-9">
			<input class="form-control" type="text" name="book_id" required/>
			</div>
			</div>
			<div class="form-group">
			<label class="col-md-3 control-label">Category</label>
			<div class="col-md-9">
			<input class="form-control" type="text" name="category" required/>	
			</div>
			</div>
			<div class="form-group">
			<label class="col-md-3 control-label">Book Name</label>	
			<div class="col-md-9">
			<input class="form-control" type="text" name="name" required/>	
			</div>
			</div>
			<div class="form-group">
			<label class="col-md-3 control-label">Publish Company</label>
			<div class="col-md-9">
			<input class="form-control" type="text" name="pub_com" required/>	
			</div>
			</div>
			<div class="form-group">
			<label class="col-md-3 control-label">Publish Year</label>
			<div class="col-md-9">
			<input class="form-control" type="text" name="pub_year" required/>
			</div>
			</div>
			<div class="form-group">
			<label class="col-md-3 control-label">Author</label>
			<div class="col-md-9">
			<input class="form-control" type="text" name="author" required/>
			</div>
			</div>
			<div class="form-group">
			<label class="col-md-3 control-label">Price</label>
			<div class="col-md-9">
			<input class="form-control" type="text" name="price" required/>	
			</div>
			</div>
			<div class="form-group">
			<label class="col-md-3 control-label">amount</label>
			<div class="col-md-9">
			<input class="form-control" type="text" name="amount" required/>
			</div>
			</div>
			<button type="submit" id="add-book-submit" class="btn btn-primary pull-right">Submit</button>
		</form>
	</div>
	<div class="mng-tag hidden" id="del-book-tag">
		<form class="form-horizontal">
			<div class="form-group">
			<label class="col-md-3 control-label">Book ID</label>	
			<div class="col-md-9">
			<input class="form-control" type="text" name="book_id" required/>	
			</div>
			</div>
			<button type="submit" id="del-book-submit" class="btn btn-primary pull-right">Submit</button>
		</form>
	</div>
	<div class="mng-tag hidden" id="del-card-tag">
		<form class="form-horizontal">
			<div class="form-group">
			<label class="col-md-3 control-label">Card ID</label>
			<div class="col-md-9">
			<input class="form-control" type='text' name="card_id" required/>
			</div>
			</div>
			<button type="submit" id="del-card-submit" class="btn btn-primary pull-right">Submit</button>
		</form>
	</div>
	<div class="mng-tag hidden" id="add-card-tag">
		<form class="form-horizontal">
			<div class="form-group">
			<label class="col-md-3 control-label">Card ID</label>
			<div class="col-md-9">
			<input class="form-control" type='text' name="card_id" required/>
			</div>
			</div>
			<div class="form-group">
			<label class="col-md-3 control-label">Borrowing Limit</label>
			<div class="col-md-9">
			<input class="form-control" type='text' name="limit" required/>
			</div>
			</div>
			<div class="form-group">
			<label class="col-md-3 control-label">Card Type</label>
			<div class="col-md-9">
			<input class="form-control" type='text' name="card_type" required/>
			</div>
			</div>
			<button type="submit" id="add-card-submit" class="btn btn-primary pull-right">Submit</button>
		</form>
	</div>
	<div class="mng-tag hidden" id="book-borrow-tag">
		<form class="form-horizontal">
			<div class="form-group">
			<label class="col-md-3 control-label">Card ID</label>
			<div class="col-md-9">
			<input class="form-control" type='text' name="card_id" required/>
			</div>
			</div>
		<div class="form-group">
			<label class="col-md-3 control-label">Book</label>
			<div class="col-md-9">
			<input class="form-control" type='text' name="book_id" required/>
			</div>
			</div>
			<button type="submit" id="book-borrow-submit" class="btn btn-primary pull-right">Submit</button>
			<button type="button" class="btn btn-primary pull-right search-card-book">Borrowed</button>
		</form>
	</div>
	<div class="mng-tag hidden" id="book-return-tag">
		<form class="form-horizontal">
			<div class="form-group">
			<label class="col-md-3 control-label">Card ID</label>
			<div class="col-md-9">
			<input class="form-control" type='text' name="card_id" required/>
			</div>
			</div>
		<div class="form-group">
			<label class="col-md-3 control-label">Book</label>
			<div class="col-md-9">
			<input class="form-control" type='text' name="book_id" required/>
			</div>
			</div>
			<button type="submit" id="book-return-submit" class="btn btn-primary pull-right">Submit</button>
			<button type="button" class="btn btn-primary pull-right search-card-book">Borrowed</button>
		</form>
	</div>
	<div class="mng-tag hidden" id="book-file-tag">
		<form>
			<div class="form-group">
			<h4 style="margin-bottom: 1em;">Usage:</h4>
			<div class="col-md-3">
				<p>Add Book: </p>
				<p>Delete Book:</p>
			</div>
			<div class="col-md-3">
				<p><code>add_book</code></p>
				<p><code>del_book</code></p>
			</div>
			<div class="col-md-3">
				<p>Add Card: </p>
				<p>Delete Card:</p>
			</div>
			<div class="col-md-3">
				<p><code>add_card</code></p>
				<p><code>del_card</code></p>
			</div>
			</div>
			<button type="submit" id="book-file-submit" class="btn btn-primary pull-right">Submit</button>
		<input type="file" name="f"></input>
		</form>
	</div>
	<ul id="info">
		
	</ul>
</div>
</div>
{% endblock %}
{% block staticJS %}
<script src="{% static 'books/js/libadmin.js' %}"></script>
{% endblock %}

books/templates/books/login.html
{% extends "books/base.html" %}

{% block container %}
{% if msg %}
<div id="message" class="alert alert-danger" role="alert">
    {{ msg }}
</div>
{% endif %}
<form action="{% url 'books:loginConfirm' %}" method="post">
{% csrf_token %}
    <label>Username</label>
    <input type="text" name="username">
    <br>
    <label>Password</label>
    <input type="text" name="password">
    <br>
    <button type="submit" class="btn btn-default">Submit</button>
</form>
{% endblock %}

books/templates/books/search.html
{% extends "books/base.html" %}
{% load staticfiles %}

{% block staticCSS %}
<link rel="stylesheet" href="{% static 'books/css/search.css' %}"/>
{% endblock %}

{% block container %}
{% if none %}
    <div id="message" class="alert alert-danger" role="alert">Oh, No book matched</div>
{% else %}
	<div id="message" class="alert alert-danger" role="alert" style="display: none;"></div>
{% endif %}

<form class="form-inline">
	<div class="form-group">
		<input type="text" class="form-control" name="content" id="search-content" placeholder="Please type the book you want">
	</div>
	<button type="submit" class="btn btn-primary" id="search-submit">Search</button>
</form>

{% if not none %}
	<ul id="info" class="nav">
	{% for book in books %}
	    <li class="search-item">
	    	<span class="book-id">{{ book.book_id }}</span>
	    	<span class="book-category">{{ book.category }}</span>
	    	<span class="book-name">{{ book.name }}</span>
	    	<span class="book-pub-com">{{ book.pub_com }}</span>
	    	<span class="book-pub-year">{{ book.pub_year }}</span>
	    	<span class="book-author">{{ book.author }}</span>
	    	<span class="book-price">{{ book.price }}</span>
	    	<span class="book-left">{{ book.left }}</span>
	    </li>
	{% endfor %}
	</ul>
{% endif %}
{% endblock %}

{% block staticJS %}
<script src="{% static 'books/js/search.js' %}"></script>
{% endblock %}